import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Recommendation } from "./store.js";

export function slugForEmail(email: string): string {
  const local = email.split("@")[0] ?? email;
  return local
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function urgencyHeader(urgency: Recommendation["urgency"]): string {
  return urgency.charAt(0).toUpperCase() + urgency.slice(1) + " urgency";
}

function renderAction(r: Recommendation): string {
  const lines: string[] = [];
  lines.push(`### ${r.title}`);
  lines.push("");
  lines.push(r.rationale);
  lines.push("");
  lines.push(`- **Confidence:** ${r.confidence}`);
  lines.push(`- **Scope:** ${r.scope}`);
  if (r.evidence.length > 0) {
    lines.push(`- **Evidence:** ${r.evidence.join(", ")}`);
  }
  lines.push("");
  return lines.join("\n");
}

export function writePerPersonFile(
  libPath: string,
  assigneeEmail: string,
  recs: Recommendation[],
): string {
  const recsDir = join(libPath, "recommendations");
  mkdirSync(recsDir, { recursive: true });
  const slug = slugForEmail(assigneeEmail);
  const path = join(recsDir, `${slug}.md`);

  const now = new Date().toISOString();
  const total = recs.length;

  const lines: string[] = [];
  lines.push("---");
  lines.push(`title: Recommendations for ${assigneeEmail}`);
  lines.push(`generated_at: ${now}`);
  lines.push(`total_actions: ${total}`);
  lines.push("---");
  lines.push("");

  if (total === 0) {
    lines.push("# What's on your plate");
    lines.push("");
    lines.push("_Nothing on your plate right now._");
    writeFileSync(path, lines.join("\n"));
    return path;
  }

  lines.push("# What's on your plate");
  lines.push("");
  lines.push(`_Generated by JR Oracle._`);
  lines.push("");

  for (const urgency of ["high", "medium", "low"] as const) {
    const group = recs.filter((r) => r.urgency === urgency);
    if (group.length === 0) {
      continue;
    }
    lines.push(`## ${urgencyHeader(urgency)}`);
    lines.push("");
    for (const r of group) {
      lines.push(renderAction(r));
    }
  }

  writeFileSync(path, lines.join("\n"));
  return path;
}
